USE OnHold;
GO

ALTER TABLE Customers WITH CHECK
ADD CONSTRAINT FK_CustZipCodes FOREIGN KEY(ZipCode) 
	REFERENCES ZipCodes(ZipCode)
ON UPDATE CASCADE
GO

ALTER TABLE Employees WITH CHECK
ADD CONSTRAINT FK_EmpZipCodes FOREIGN KEY(ZipCode) 
	REFERENCES ZipCodes(ZipCode)
ON UPDATE CASCADE
GO

ALTER TABLE Employees WITH CHECK
ADD CONSTRAINT FK_JobID FOREIGN KEY(JobID) 
	REFERENCES Jobs(JobID)
ON UPDATE CASCADE
GO

ALTER TABLE Employees WITH CHECK
ADD CONSTRAINT FK_DeptID FOREIGN KEY(DeptID) 
	REFERENCES Departments(DeptID)
ON UPDATE CASCADE
GO

ALTER TABLE OnHoldItems WITH CHECK
ADD CONSTRAINT FK_CustomerID FOREIGN KEY(CustomerID) 
	REFERENCES Customers(CustID)
ON UPDATE CASCADE
GO

ALTER TABLE OnHoldItems WITH CHECK
ADD CONSTRAINT FK_HoldReason FOREIGN KEY(HoldReason) 
	REFERENCES HoldReasons(HoldCode)
ON UPDATE CASCADE
GO

ALTER TABLE OnHoldItems WITH CHECK
ADD CONSTRAINT FK_EmployeeID FOREIGN KEY(EmployeeID) 
	REFERENCES Employees(EmployeeID)


ALTER TABLE OnHoldItems WITH CHECK
ADD CONSTRAINT FK_DispositionCode FOREIGN KEY(DispositionCode) 
	REFERENCES Dispositions(DispositionCode)
ON UPDATE CASCADE
GO
